/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    DailyReportDialog: typeof import('./src/components/pages/dailyReport/DailyReportDialog.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DefaultLayout: typeof import('./src/components/layouts/DefaultLayout.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FormResolver: typeof import('./src/components/utils/FormResolver.vue')['default']
    FormStepper: typeof import('./src/components/utils/FormStepper.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StartNotificationDialog: typeof import('./src/components/pages/startNotification/StartNotificationDialog.vue')['default']
    TaskActual: typeof import('./src/components/pages/dailyReport/TaskActual.vue')['default']
    TaskScheduled: typeof import('./src/components/pages/dailyReport/TaskScheduled.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    WorkDateTime: typeof import('./src/components/utils/WorkDateTime.vue')['default']
    WorkTaskRecord: typeof import('./src/components/utils/WorkTaskRecord.vue')['default']
  }
}
